MyBooks/ViewComponents/BookStatisticsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyBooks.Data.AuthorsRepository;
using MyBooks.Data.BooksRepository;
using MyBooks.Data.OrderBooksRepository;
using MyBooks.Entity.ViewModels;

namespace MyBooks.ViewComponents
{
    public class BookStatisticsViewComponent: ViewComponent
    {
        private readonly IAuthorsRepository _authorsrepo;
        private readonly IBooksRepository _booksrepo;
        private readonly IOrderBooksRepository _orderbooksrepo;
        public BookStatisticsViewComponent(IAuthorsRepository authorsrepo,IBooksRepository booksrepo,IOrderBooksRepository orderbooksrepo)
        {
            _authorsrepo = authorsrepo;
            _booksrepo = booksrepo;
            _orderbooksrepo = orderbooksrepo;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var statistics = new StatisticsViewModel();
            statistics.AuthorsCount = await _authorsrepo.AuthorsCount();

            statistics.BooksCount = await _booksrepo.GetBooksCount();

            statistics.OrdersCount = await _orderbooksrepo.GetOrdersCount();
            return View(statistics);
        }
    }
}

MyBooks/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyBooks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <img src="~/images/bookstore.jpg" style="width: 100px; height: 100px;"/>
        <a class="navbar-brand" asp-page="/Index">My Book Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-page="/Index">Home </a>

                    @*<a class="nav-link" href="#">Home <span class="sr-only" asp-page="/Index">(current)</span></a>*@
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Masters
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="nav-link" asp-page="/AuthorsMaster/Index">Authors</a>

                        <a class="nav-link" asp-page="/BooksMaster/Index">Books</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Transactions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="nav-link" asp-page="/OrderBooks/Create">Order Books</a>
                    </div>
                </li>
                @if (Context.User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="javascript:;">Hello @User.Identity.Name!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/account/SignOut">SignOut</a>
                    </li>
                }
            </ul>
            @*<form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>*@
        </div>
    </nav>
    @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MyBooks</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a href="#">File</a>
                            <ul class="submenu">
                                <li><a href="#">Close</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Transactions</a>
                        </li>
                    </ul>
                </div>
            </div>


        </nav>*@
</header>
<welcome-message name="@MyBooks.Entity.Global.GlobalVariables.UserName"></welcome-message>
<div class="col-md-12">
    @*@await Component.InvokeAsync("BookStatistics")*@
    <vc:book-statistics></vc:book-statistics>
</div>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
@*<div class="col-md-12">
    @await  Component.InvokeAsync("BookStatistics")
    <vc:book-statistics></vc:book-statistics>
</div>*@

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyBooks - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>